apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: backend
        image: viatab-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        command: ["java"]
        args: [
          "-Dspring.datasource.url=jdbc:postgresql://postgres-service:5432/viatab",
          "-Dspring.datasource.username=viatab_user",
          "-Dspring.datasource.password=viatab_password",
          "-jar",
          "app.jar"
        ]
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP